templates:
  params:
    author-name: Christian Gram Kalhauge
    author-email: kalhauge@cs.ucla.edu
    copyright: BSD-3-Clause
    github-username: kalhauge
nix:
  enable: true
  packages: 
    - glpk
    - pcre
    - zlib
    - bzip2
    - clang
    - darwin.apple_sdk.frameworks.Cocoa
    - darwin.apple_sdk.frameworks.CoreServices
    - pkgconfig
    - cairo
