templates:
  params:
    author-name: Christian Gram Kalhauge
    author-email: kalhauge@cs.ucla.edu
    copyright: MIT
    github-username: kalhauge

nix:
  enable: true
  packages: 
    - glpk
    - pcre
    - zlib
